server:
  port: 9090

spring:
  application:
    name: msvc-student

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname:localhost
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka