server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: courses
          uri: http://localhost:8090
          predicates:
            - Path=/api/course/**

        - id: students
          uri: http://localhost:9090
          predicates:
            - Path=/api/student/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false