server:
  port: 8090

spring:
  application:
    name: msvc-courses

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/courses
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
